apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: middleware
  name: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: middleware
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: middleware
    spec:
      containers:
        - image: middleware
          name: middleware
          ports:
            - containerPort: 8081
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
