version: "3"
services:
  client:
    build: # node:current-alpine3.12 # artifatory url
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    links:
      - middleware
    depends_on:
      - middleware
    volumes:
      -  clientdata:/app
      - ../client/src:/app/src:cached 
    tty: true

  middleware:
    build:
      context: ../middleware
      dockerfile: Dockerfile
      #debugger https://code.visualstudio.com/docs/containers/debug-node
    ports:
      - "8081:8081"
      - "9229:9229"
    volumes:
      -  middlewaredata:/app
      - ../middleware/src:/app/src:cached
    tty: true
    
volumes:
  clientdata:
  middlewaredata: