version: "3"
services:
  client:
    build: 
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    links:
      - middleware
    depends_on:
      - middleware
    volumes:
      -  clientdata:/app
      - ../client/src:/app/src:cached 
    tty: true

  middleware:
    build:
      context: ../middleware
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      -  middlewaredata:/app
      - ../middleware/src:/app/src:cached
    tty: true
    
volumes:
  clientdata:
  middlewaredata: