#!/bin/bash
docker-compose -p fnx-cloud -f ./dc/docker-compose.yml -f ./dc/docker-compose.dev.yml up -d --remove-orphans "$@"
echo '
  ___ _  ___  __   ___ _             _ 
 | __| \| \ \/ /  / __| |___ _  _ __| |
 | _|| .` |>  <  | (__| / _ \ || / _` |
 |_| |_|\_/_/\_\  \___|_\___/\_,_\__,_|

        🚀 Awesome portal 🚀
  -------------------------------------
  middleware 🤖  http://localhost:8081
  client     ⛏   http://localhost:4000 
  
'

#open http://localhost:4000